### ISSUE TITLE
question about multi_rtl_source

### ISSUE THREAD

**Issue by bdyaods** [ptrkrysik/multi-rtl#1]
hi
   I want to capture the GSM downlink and uplink data, my hardware is binded  two RTL-SDR dongles, software is mutlirtl_rx_to_cfile_2chan.py with multi_rtl_source, and I got two files, one for downlink, one for uplink. When I decoding them with uplink_decoding_multi_rtl.py, it seems something wrong. There are several decoded messages displayed as "Uplink", but they are actually downlink data, and there is no any other uplink message until the end. It seems the script saved some data before the two dongles were synchronized.
   How can resolve this problem and got the uplink messages?
   Best regards!

**Comment by ptrkrysik** [comment]
W dniu 24.09.2016 o 17:37, bdyaods pisze:

> hi
> I want to capture the GSM downlink and uplink data, my hardware is
> binded two RTL-SDR dongles, software is mutlirtl_rx_to_cfile_2chan.py
> with multi_rtl_source, and I got two files, one for downlink, one for
> uplink. When I decoding them with uplink_decoding_multi_rtl.py, it seems
> something wrong. There are several decoded messages displayed as
> "Uplink", but they are actually downlink data, and there is no any other
> uplink message until the end. It seems the script saved some data before
> the two dongles were synchronized.
> How can resolve this problem and got the uplink messages?
> Best regards!

Hi bdyaods,

It's great that you are trying to use Multi-RTL.

Regarding helping you to get it working - I will need more information
to figure out what the problem might be.
1. find some GSM C0 channel frequency,
2. edit the octave script
   https://github.com/ptrkrysik/multi-rtl/blob/master/examples/test_multirtl.m
   and replace values of these parameters:
   "--freq-ch0=939.4e6 --freq-ch1=939.4e6 --sync-freq=939.4e6"
   with the frequency that you have found.
3. install octave
4. run the examples/test_multirtl.m script,
5. send me a screen-shot of the plot that will (hopefully) be drawn.

P.S. can you subscribe to the list:
https://github.com/ptrkrysik/multi-rtl/#mailing-list
so we can continue there?

## 

Best Regards,
Piotr Krysik

**Comment by bdyaods** [comment]
Hi, ptrkrysik
I posted a topic in multi-rtl mailing list with screen shots.
Thanks.

**Comment by bdyaods** [comment]
The sdcch channel is sdcch4 on ts0 not sdcch8 on ts1. I changed the decoder then uplink data shown.
