### ISSUE TITLE
bad alloc exception about vector_sink

### ISSUE THREAD

**Issue by bdyaods** [ptrkrysik/multi-rtl#2]
hi, ptrkrysik:
after the multi-rtl runs for a long time, the stream will be blocked (Overrun). I found the variable d_data grow up infinitely , the code is in vector_sink_cn_impl.cc, line 117 to 120, I commented them, and the multi-rtl can run day and night. is there any other side effects?
  thanks.

**Comment by ptrkrysik** [comment]
@bdyaods

Many thanks for reporting this. Theoretically when Multi-RTL is used
program shouldn't go to these lines of the code. But if commenting them
have the effect you described then there is something wrong with the
vector sink or the way it is used.

**Comment by ptrkrysik** [comment]
@bdyaods - can you pull the newest revision and check if it works correctly now?

**Comment by ptrkrysik** [comment]
I checked it and after the commit 506d66fc584c28342deb41bd4c4e34b015b4d47e Multi-RTL stopped eating memory. In case you find that something is still wrong I will reopen the issue. Many thanks for helping to improve Multi-RTL :)

**Comment by bdyaods** [comment]
I pulled the newest version, It works well. 
Thank you for your efforts on these projects.
