### ISSUE TITLE
error when  running example: 'module' object has no attribute 'vector_sink_cn'

### ISSUE THREAD

**Issue by Armineus** [ptrkrysik/multi-rtl#3]
I have installed the plugin, first head then other revisions. All I get is this mysterious message.
Here is the output of the terminal:

 ./examples/test_sync.py 
linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.9
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 1083333.009279 Hz
[R82XX] PLL not locked!
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.9
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy redpitaya 
Using device #1 Realtek RTL2838UHIDIR SN: 00000002
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 1083333.009279 Hz
[R82XX] PLL not locked!
setting freq corr -7
Traceback (most recent call last):
  File "./examples/test_sync.py", line 100, in <module>
    tb = test_sync()
  File "./examples/test_sync.py", line 62, in __init__
    "31", 
  File "/usr/local/lib/python2.7/dist-packages/multi_rtl/multi_rtl_source.py", line 149, in __init__
    self.vsink = multi_rtl.vector_sink_cn(1, True, int(self.sync_samples), int(num_channels), self.vsink_notifier)
AttributeError: 'module' object has no attribute 'vector_sink_cn'

**Comment by ptrkrysik** [comment]
@armineus, thank you for reporting this problem. I will look into it.

**Comment by ptrkrysik** [comment]
Try to execute:

sudo ldconfig

(or ldconfig as root) and let me know if it works.

**Comment by Armineus** [comment]
Hi Piotr,
Thx for your fast reply.
I did ldconfig but error is the same

Best regards ,

Stefan Groißmeier

**Comment by ptrkrysik** [comment]
W dniu 31.12.2016 o 15:19, armineus pisze:
> I have installed the plugin, first head then other revisions. All I get
> is this mysterious message.
> Here is the output of the terminal:
> 
> ./examples/test_sync.py
...

test_sync.py script is gone since the end of May (before official
release of Multi-RTL). Please try to install current version from the
repository and try again.

**Comment by Armineus** [comment]
Hi Piotr,

it works now. It seemed the first time ever git has not checked out the whole repository.
I then had another error: " could not import multi sdr swig". I've then installed swig and voila it works.

I have written a small patch that would add an meaningful fatal error message when cmake can't find the package.

thx,

Steve

**Comment by Armineus** [comment]
Here it is:

[patch.txt](https://github.com/ptrkrysik/multi-rtl/files/683100/patch.txt)
